### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by Mnky313** [BelgianSalamander/MoreBundles#3]
I'm back again xD

Just tried to add the mod to a dedicated server and it crashes when trying to start the server.

`[19:40:39] [main/INFO]: [STDOUT]: Reading config values from file.
[19:40:39] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morebundles'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.8.jar:?]
        at net.minecraft.server.Main.main(Main.java:102) [intermediary-server-1.18.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.nio.file.Path.resolve(String)" because the return value of "java.nio.file.Path.getParent()" is null
        at me.salamander.morebundles.common.gen.MoreBundlesConfig.registerTextures(MoreBundlesConfig.java:243) ~[morebundles-0.1.3.jar:?]
        at me.salamander.morebundles.MoreBundles.onInitialize(MoreBundles.java:70) ~[morebundles-0.1.3.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more`

Here's the full log:
[server.log](https://github.com/BelgianSalamander/MoreBundles/files/7696112/server.log)

There's a bunch of other mods installed but the client works fine with the same mods. The same crash occurs when running with just fabric api and more bundles.

**Comment by BelgianSalamander** [comment]
This error is caused when it tries to save generated textures and for some reason the parent of the game directory is null. Although I don't know why the parent would be null, putting it outside of the game directory is definitely a bad idea on my part. I'll release a fix soon

**Comment by BelgianSalamander** [comment]
Hello! Could you confirm that the issue is fixed with this version?

[https://file.io/hUqBBBgfTDIx](https://file.io/hUqBBBgfTDIx)
(This is an external link because github issues does not support uploading JAR files)

**Comment by Mnky313** [comment]
> 

Nope, same crash (at least it looks the same, I put the log in again in case it's not.)

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morebundles'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.8.jar:?]
        at net.minecraft.server.Main.main(Main.java:102) [intermediary-server-1.18.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at me.salamander.morebundles.common.gen.TextureGen.getMinecraftTexture(TextureGen.java:176) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.TextureGen.<clinit>(TextureGen.java:23) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.BundleInfo$BundleTextureInfo.lambda$fromJson$0(BundleInfo.java:170) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.MoreBundlesConfig.registerTextures(MoreBundlesConfig.java:250) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.MoreBundles.onInitialize(MoreBundles.java:70) ~[morebundles-0.1.3+patch-1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.salamander.morebundles.common.gen.TextureGen.getMinecraftTexture(TextureGen.java:176) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.TextureGen.<clinit>(TextureGen.java:23) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.BundleInfo$BundleTextureInfo.lambda$fromJson$0(BundleInfo.java:170) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.MoreBundlesConfig.registerTextures(MoreBundlesConfig.java:250) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.MoreBundles.onInitialize(MoreBundles.java:70) ~[morebundles-0.1.3+patch-1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more
```

**Comment by BelgianSalamander** [comment]
This is a different error but I just realized that the server should not be generating textures. Hopefully this isn't too hard to fix.

**Comment by BelgianSalamander** [comment]
I think this should fix it.

[https://file.io/KxcMOHeRoAH4](https://file.io/KxcMOHeRoAH4)

**Comment by Mnky313** [comment]
> 

Nope.

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morebundles'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.8.jar:?]
        at net.minecraft.server.Main.main(Main.java:102) [intermediary-server-1.18.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:599) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.8.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.8.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
        at me.salamander.morebundles.common.gen.TextureGen.getMinecraftTexture(TextureGen.java:176) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.TextureGen.<clinit>(TextureGen.java:23) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.BundleInfo$BundleTextureInfo.lambda$fromJson$0(BundleInfo.java:170) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.MoreBundlesConfig.registerTextures(MoreBundlesConfig.java:250) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.MoreBundles.onInitialize(MoreBundles.java:70) ~[morebundles-0.1.3+patch-1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.8.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.salamander.morebundles.common.gen.TextureGen.getMinecraftTexture(TextureGen.java:176) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.TextureGen.<clinit>(TextureGen.java:23) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.BundleInfo$BundleTextureInfo.lambda$fromJson$0(BundleInfo.java:170) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.common.gen.MoreBundlesConfig.registerTextures(MoreBundlesConfig.java:250) ~[morebundles-0.1.3+patch-1.jar:?]
        at me.salamander.morebundles.MoreBundles.onInitialize(MoreBundles.java:70) ~[morebundles-0.1.3+patch-1.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.8.jar:?]
        ... 15 more
```

**Comment by BelgianSalamander** [comment]
Third time's the charm!

[https://file.io/wt3VatVGTwov](https://file.io/wt3VatVGTwov)

**Comment by BelgianSalamander** [comment]
Can you confirm whether or not it worked?

**Comment by Mnky313** [comment]
Sorry, I got distracted with some other stuff.

Yep, works fine now!

Thanks!

**Comment by BelgianSalamander** [comment]
Thanks for testing it :)
